name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure and reload Docker daemon to allow for bigger shm
      run: |
        echo '{ "cgroup-parent": "/actions_job", "default-shm-size": "512M" }' | sudo tee /etc/docker/daemon.json && sudo systemctl reload docker
    - uses: actions/checkout@v1
      with:
        ref: master
        fetch-depth: 1
    - name: Build release through PrepareForUpload.sh
      run: |
        set +x
        # the name of the repo, without the author
        devDir="hoi4-mod-test"
        # the name of the target mod folder
        destDir="hoi4_mod_test"
        chmod +x ./PrepareForUpload.sh
        ./PrepareForUpload.sh $devDir $destDir thumbnail.jpg
        mkdir build
        mv ../$destDir build
        mv ../"$destDir.mod" build
        cd build
        cat "$destDir.mod"
        zip -rq "$destDir.zip" .
        mv "$destDir.zip" ..
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: hoi4_mod_test.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Steam Workshop
      uses: Yard1/PDX-Steam-Workshop-Publisher-Action@master
      with:
        steamLogin: LOGIN
        steamPassword: ${{ secrets.STEAMPASSWORD }}
        PDXLogin: EMAIL
        PDXPassword: ${{ secrets.PDXPASSWORD }}
        modPath: "build"
        POP3Address:  ${{ secrets.POP3ADDRESS }}
        POP3User: ${{ secrets.POP3USER }}
        POP3Password: ${{ secrets.POP3PASSWORD }}
        debugImagePath: images
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: debug_images
        path: images